### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: None

### ISSUE THREAD

**Issue by Ruke805** [digitalec/deemon#114]
Hi, I'm getting this error when I try to refresh:

`Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\deemon.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\deemon\__main__.py", line 5, in main
    cli.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\deemon\cli.py", line 98, in run
    if parse_version(new_version) > parse_version(__version__):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'`

My version is 2.20, python 3.7

Do you know what can be the reason?

**Comment by digitalec** [comment]
Please upgrade to 2.21.3 to fix this.

`pip install --upgrade deemon`

**Comment by Ruke805** [comment]
It does not upgrade to this version using python.3.7
If I install the most recent python version, will work normally, or i need to backup and migrate the data, something like this?

**Comment by digitalec** [comment]
You can use the following to bypass the Python version requirement:

`pip install --upgrade --ignore-python-requires deemon`

I only support 3.8 or higher since 3.7 is EOL.

**Comment by Ruke805** [comment]
I upgraded but did not work..is there a way to migrate to python 3.8? Or I'll lose the data?
