### ISSUE TITLE
cant download using Artists.txt file

### ISSUE THREAD

**Issue by mecaz** [digitalec/deemon#12]
Hello, 

I created an Artists.txt file contains all of my following artists. 
But i can not download by that file 
It gives me following error.

"deemon download --artist ArtistName" command works sucessfully by the way

deemon download --file /music/Artists.txt 
Verifying ARL is valid, please wait...
Reading from file /music/Artists.txt
Traceback (most recent call last):
  File "/usr/bin/deemon", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/deemon/__main__.py", line 4, in main
    cli.run()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/deemon/cli.py", line 73, in download_command
    dl.download(params)
  File "/usr/lib/python3.8/site-packages/deemon/app/download.py", line 103, in download
    artist = self.dz.api.search_artist(name, limit=1)['data'][0]
IndexError: list index out of range

**Comment by digitalec** [comment]
You're getting the IndexError because an artist in your file wasn't found on Deezer. I'll add appropriate error handling in this situation

**Comment by digitalec** [comment]
Issue fixed in 1.0.5
