### ISSUE TITLE
UnicodeDecodeError on Windows (download --file)

### ISSUE THREAD

**Issue by digitalec** [digitalec/deemon#17]
```
Reading from file /srv/8ff25b7d-55d3-4cc7-bef9-a07257edfe47/data/artists.txt
Traceback (most recent call last):
  File "/usr/local/bin/deemon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/deemon/__main__.py", line 4, in main
    cli.run()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deemon/cli.py", line 74, in download_command
    dl.download(params)
  File "/usr/local/lib/python3.7/dist-packages/deemon/app/download.py", line 109, in download
    make_csv = f.read().replace('\n', ',')
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 1325: invalid start byte
```

**Comment by digitalec** [comment]
Fixed. Will be in 1.2-beta3
