### ISSUE TITLE
ModuleNotFoundError: No module named 'deezer.errors' — after updating to version 1.3.

### ISSUE THREAD

**Issue by mathiasfoster** [digitalec/deemon#34]
After upgrading to 1.3 (with pip), I get the following error when running any deemon commands:
```
Traceback (most recent call last):
  File "/usr/local/bin/deemon", line 5, in <module>
    from deemon.__main__ import main
  File "/home/mathias/.local/lib/python3.8/site-packages/deemon/__main__.py", line 1, in <module>
    from deemon import cli
  File "/home/mathias/.local/lib/python3.8/site-packages/deemon/cli.py", line 1, in <module>
    from deemon.app import settings, monitor, download, notify, utils
  File "/home/mathias/.local/lib/python3.8/site-packages/deemon/app/download.py", line 5, in <module>
    from deemon.app import dmi, Deemon, utils
  File "/home/mathias/.local/lib/python3.8/site-packages/deemon/app/dmi.py", line 2, in <module>
    import deemix
  File "/home/mathias/.local/lib/python3.8/site-packages/deemix/__init__.py", line 5, in <module>
    from deemix.itemgen import generateTrackItem, \
  File "/home/mathias/.local/lib/python3.8/site-packages/deemix/itemgen.py", line 4, in <module>
    from deezer.errors import GWAPIError, APIError
ModuleNotFoundError: No module named 'deezer.errors'
```

**Comment by digitalec** [comment]
I had that issue when deemix 3.4.2 was released.

Uninstall:
`pip uninstall deemix deezer-py deemon`

Then install deemon:
`pip install deemon`

**Comment by mathiasfoster** [comment]
The above worked!
I did have to upgrade deemon afterwards, from 1.0.7 to 1.3:
`sudo pip3 install --upgrade deemon`
