### ISSUE TITLE
Crash when attempting to use time-machine via monitor

### ISSUE THREAD

**Issue by Critical-Impact** [digitalec/deemon#50]
Hi, I am attempting to run a monitor import to set up the initial artists and want to start them off at the start of last year
I do something like(I'm using docker so cut that out) deemon monitor --import /downloads/artists.txt --download -T 2021-01-01

I get the error
```
:: Fetching artist data for 16 artist(s), please wait... 100%
:: Examining results for best match... 100%
:: Setting up artists for monitoring... 100%
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/deemon/__main__.py", line 9, in <module>
    main()
  File "/app/deemon/__main__.py", line 5, in main
    cli.run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/deemon/cli.py", line 240, in monitor_command
    monitor.importer(im)
  File "/app/deemon/cmd/monitor.py", line 204, in importer
    self.artists(artist_list)
  File "/app/deemon/cmd/monitor.py", line 173, in artists
    self.call_refresh()
  File "/app/deemon/cmd/monitor.py", line 145, in call_refresh
    refresh = Refresh(self.time_machine, ignore_filters=self.dl)
  File "/app/deemon/cmd/refresh.py", line 32, in __init__
    logger.info(f":: Time Machine active: {datetime.strftime(self.time_machine, '%b %d, %Y')}!")
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'list' object


```

**Comment by digitalec** [comment]
Fixed in 2.8.2; it takes roughly 10 min for the docker image to update.
