### ISSUE TITLE
I'm getting an error when I try to add a new artist via Monitor by URL  feature

### ISSUE THREAD

**Issue by Ruke805** [digitalec/deemon#75]
I tried this command as indicated on Documentation page: deemon monitor --url https://www.deezer.com/us/artist/62400

I am using the last version

I've got this error: 

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\deemon.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\deemon\__main__.py", line 5, in main
    cli.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\deemon\cli.py", line 246, in monitor_command
    monitor.artist_ids(dataprocessor.csv_to_list(artist))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\deemon\utils\dataprocessor.py", line 52, in csv_to_list
    if artist[-1] == ',':
TypeError: 'int' object is not subscriptable
```

**Comment by digitalec** [comment]
Confirmed. Integer is being passed directly without first being put in a list.

Will patch in next release.
