### ISSUE TITLE
download playlist by URL is broken

### ISSUE THREAD

**Issue by ahurtaud** [digitalec/deemon#95]
Hello,

I am trying to download playlist by url and got a python exception.
I am using the ghcr.io/digitalec/deemon:latest docker image.

<details>
  <summary>logs</summary>
  
  ```bash
deemon download -u "https://www.deezer.com/fr/playlist/1363560485"
  
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/deemon/__main__.py", line 9, in <module>
    main()
  File "/app/deemon/__main__.py", line 5, in main
    cli.run()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/deemon/cli.py", line 183, in download_command
    dl.download(artists, artist_ids, album_ids, urls, artist_file, track_file, album_file, track_ids, monitored=monitored)
  File "/app/deemon/cmd/download.py", line 482, in download
    process_playlist_by_id(eid)
  File "/app/deemon/cmd/download.py", line 351, in process_playlist_by_id
    self.queue_list.append(QueueItem(playlist=playlist_api))
  File "/app/deemon/cmd/download.py", line 74, in __init__
    self.url = playlist["url"]
KeyError: 'url'
Verifying ARL, please wait...
[!] Queueing releases, this might take awhile...
  ```
  
</details>

I have check quickly and to me, the issue is:
The playlsit object [has an `link` attribute](https://github.com/digitalec/deemon/blob/main/deemon/core/api.py#L281) instead of [`url` to download](https://github.com/digitalec/deemon/blob/main/deemon/cmd/download.py#L74)

**Comment by MidnightAnnie** [comment]
Also getting this same issue on windows.

and its only the download --url as it has no issues with downloading when its monitored
